export enum Api{
    LOGIN = '/api/User/Login',
    REGISTER = '/api/User/Register',
    USER = '/api/User/:id',
    USER_CHATS = '/api/User',
    CHAT='/api/Chat',
    CHAT_CREATE='/api/Chat/Create',
    CHAT_ADD_USER='/api/Chat/AddUser',
    CHAT_DELETE_USER='/api/Chat/DeleteUser',
    CHAT_DELETE_CHAT='/api/Chat/:id',
    CHAT_GET='/api/Chat/:id',
    CHAT_GET_USERS='/api/Chat/GetUsers/',
    CHAT_FIND_USER='/api/Chat/FindUser',
    CHAT_GET_MESSAGES_COUNT='/api/Chat/GetMessagesCount',
    CHAT_GET_USERS_COUNT='/api/Chat/GetUsersCount',
    CHAT_ASSIGN_ADMIN='/api/Chat/AssignAdminRole',
    CHAT_GET_USER_ROLE='/api/Chat/GetUserRole',
    FILEMESSAGE='/api/FileMessage/:id',
    FILEMESSAGE_POST='/api/FileMessage',
    FILEMESSAGE_DELETE='/api/FileMessage/:id',
    FILEMESSAGE_GET='/api/FileMessage/GetNewest/:id',
    TEXTMESSAGE='/api/TextMessage/:id',
    TEXTMESSAGE_POST='/api/TextMessage',
    TEXTMESSAGE_DELETE='/api/TextMessage/:id',
    TEXTMESSAGE_GET='/api/TextMessage/GetNewest/:id',
    REFRESH_TOKEN='/api/User/RefreshToken',
    FILE='/api/File',
}
